PACKAGES:
    KIKUSUI_POWER_SUPPLY

KIKUSUI PMX:
    CMD_DELAY:  0.2   # Time between subsequent commands [s]

KIKUSUI PMX-A Control Server:
    PROTOCOL:      tcp
    PMX-A1:
        SERVICE_TYPE: PMX-A1
        PROCESS_NAME: PMX-A1
        PROTOCOL: tcp
        HOSTNAME:           localhost # The hostname that client shall connect to, e.g. pleiad01 @ KU Leuven
        COMMANDING_PORT: 0          # The port on which the controller listens to commands - REQ-REP
        MONITORING_PORT: 0          # The port on which the controller sends periodic status information of the device - PUB-SUB
        SERVICE_PORT: 0          # The port on which the controller listens for configuration and administration - REQ-REP
        METRICS_PORT: 0          # The HTTP port where Prometheus will connect to for retrieving metrics
        DELAY: 10          # The delay time between publishing status information [seconds]
        STORAGE_MNEMONIC: PMX-A1          # The mnemonic to be used in the filename storing the housekeeping data